# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_auto_20170907_1608'),
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('sender', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='ControlCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=512)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('execution', 'execution'), ('familiarization', 'familiarization'), ('execution/familiarization', 'execution/familiarization'), ('closing', 'closing'), ('finished', 'finished')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBaseProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('go_to_next_after_update', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='DocumentExecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.DeptEmp')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.DeptEmp')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('InnerLetter', 'Вхідний лист'), ('CitizensAppeal', 'Звернення громадян'), ('InformationRequest', 'Запит на інформацію'), ('OuterLetter', 'Вихідний лист'), ('DraftDecision', 'Проект рішення'), ('MayorOrdinance', 'Розпорядження міського голови'), ('MayorInstruction', 'Доручення міського голови'), ('MeetingProtocol', 'Протокол засідань'), ('OfficeMemo', 'Службова записка')], max_length=255)),
                ('type', models.CharField(choices=[('inner', 'Внутрішій'), ('outer', 'Зовнішній')], max_length=255)),
                ('is_subscriber_exist', models.BooleanField()),
                ('is_subscriber_required', models.BooleanField()),
                ('is_control_card_exist', models.BooleanField()),
                ('is_control_card_required', models.BooleanField()),
                ('is_executor_exist', models.BooleanField()),
                ('is_executor_required', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType'),
        ),
        migrations.AddField(
            model_name='controlcard',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='additionalfields',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
