# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='title',
            field=models.CharField(choices=[('InnerLetter', 'Вхідний лист'), ('CitizensAppeal', 'Звернення громадян'), ('InformationRequest', 'Запит на інформацію'), ('OuterLetter', 'Вихідний лист'), ('DraftDecision', 'Проект рішення'), ('MayorOrdinance', 'Розпорядження міського голови'), ('MayorInstruction', 'Доручення міського голови'), ('MeetingProtocol', 'Протокол засідань'), ('OfficeMemo', 'Службова записка')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type',
            field=models.CharField(choices=[('inner', 'Внутрішній'), ('outer', 'Зовнішній')], max_length=255),
        ),
    ]
