# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20170907_1608'),
        ('documents', '0002_auto_20170916_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentexecutor',
            unique_together=set([('document', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='documentsubscriber',
            unique_together=set([('document', 'employee')]),
        ),
    ]
