# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('documents', '0004_document_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizensAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InnerLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MayorInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MayorOrdinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OuterLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribers_required', models.BooleanField()),
                ('is_executors_required', models.BooleanField()),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='additionalfields',
            name='document',
        ),
        migrations.RemoveField(
            model_name='controlcard',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentbaseprocess',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentbaseprocess',
            name='process_ptr',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AdditionalFields',
        ),
        migrations.DeleteModel(
            name='ControlCard',
        ),
        migrations.DeleteModel(
            name='DocumentBaseProcess',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.AddField(
            model_name='documentprocess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
