# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20170925_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocess',
            name='go_to_next_stage',
            field=models.BooleanField(default=False),
        ),
    ]
