# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentprocess_go_to_next_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizensappeal',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='citizensappeal',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='informationrequest',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='informationrequest',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='innerletter',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='innerletter',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='mayorinstruction',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='mayorinstruction',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='mayorordinance',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='mayorordinance',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='meetingprotocol',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='meetingprotocol',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='officememo',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='officememo',
            name='is_subscribers_required',
        ),
        migrations.RemoveField(
            model_name='outerletter',
            name='is_executors_required',
        ),
        migrations.RemoveField(
            model_name='outerletter',
            name='is_subscribers_required',
        ),
    ]
