# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deptmanager',
            unique_together=set([('employee', 'department')]),
        ),
    ]
