# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20170821_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Користувач з такою електронною поштою вже існує'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
