# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170801_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['priority'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачі'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name'], 'verbose_name': 'Категорія задач', 'verbose_name_plural': 'Категорії задач'},
        ),
    ]
